/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.fic.poo.teleentrega.frames;

import br.fic.poo.teleentrega.classes.Usuario;
import br.fic.poo.teleentrega.persistencia.UsuarioDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Newton
 */
public class FramePesquisaUsuarios extends javax.swing.JInternalFrame {

    private FrameUsuarios frameUsuario;
    private UsuarioDAO daoUsuario;
    private ArrayList<Usuario> listaUsuarios;
    
    /**
     * Creates new form FramePesquisaUsuarios
     */
    public FramePesquisaUsuarios(FrameUsuarios frameUsuario, UsuarioDAO daoUsuario) {
        initComponents();
        this.frameUsuario = frameUsuario;
        this.daoUsuario = daoUsuario;
        
        //DefaultTableModel modelo = new DefaultTableModel();
        //tabela não-editável:
        DefaultTableModel modelo = 
                new DefaultTableModel(null,new Object[]{}) 
                {
                 public boolean isCellEditable(int row, int col)
                 {  return false; } 
                };
        
        modelo.addColumn("Código");
        modelo.addColumn("Nome");
        modelo.addColumn("Telefone");
        modelo.addColumn("CPF");
        //tablePesquisa.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        //tablePesquisa.getTableHeader().setReorderingAllowed(false); //Não deixa o usuário mexer na sequencia das colunas  
        tablePesquisa.getColumnModel().getColumn(0).setPreferredWidth(5); //largura da coluna  
        //tablePesquisa.getColumnModel().getColumn(1).setPreferredWidth(50); //largura da coluna    
        //tablePesquisa.setSelectionMode(ListSelectionModel.SINGLE_SELECTION); //permite selecionar apenas uma linha na tabela          //tablePesquisa.getColumnModel().getColumn(0).setMaxWidth(10);
        //tablePesquisa.getTableHeader().getColumnModel().getColumn(1).setMaxWidth(20);
        //tablePesquisa.getColumnModel().getColumn(0).setPreferredWidth(20);
        //tablePesquisa.getColumnModel().getColumn(1).setMaxWidth(10);
        //tablePesquisa.getColumnModel().getColumn(2).setMinWidth(30);
        //tablePesquisa.getColumnModel().getColumn(3).setWidth(40);
        //tablePesquisa.getTableHeader().getColumnModel(3).getColumn(3).setWidth(20);
        tablePesquisa.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePesquisa = new javax.swing.JTable();
        panelPesquisa = new javax.swing.JPanel();
        labelPesquisar = new javax.swing.JLabel();
        textPesquisar = new javax.swing.JTextField();
        btnPesquisaNome = new javax.swing.JRadioButton();
        btnPesquisaTelefone = new javax.swing.JRadioButton();
        btnPesquisar = new javax.swing.JButton();
        btnSelecionar = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setTitle("Sistema de Tele-Entregas : Pesquisa de Usuários...");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, panelPesquisa, org.jdesktop.beansbinding.ELProperty.create("${background}"), this, org.jdesktop.beansbinding.BeanProperty.create("background"));
        bindingGroup.addBinding(binding);

        tablePesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablePesquisa);

        panelPesquisa.setBackground(new java.awt.Color(255, 255, 204));
        panelPesquisa.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Pesquisar Usuários do Sistema no Cadastro ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 255))); // NOI18N
        panelPesquisa.setForeground(new java.awt.Color(0, 0, 255));
        panelPesquisa.setToolTipText("");

        labelPesquisar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelPesquisar.setText("Digite Texto para Pesquisar");

        btnPesquisaNome.setBackground(new java.awt.Color(255, 255, 204));
        btnPesquisaNome.setSelected(true);
        btnPesquisaNome.setText("por Nome");

        btnPesquisaTelefone.setBackground(new java.awt.Color(255, 255, 204));
        btnPesquisaTelefone.setText("por Telefone");

        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/fic/poo/teleentrega/imagens/page_white_lightning.png"))); // NOI18N
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPesquisaLayout = new javax.swing.GroupLayout(panelPesquisa);
        panelPesquisa.setLayout(panelPesquisaLayout);
        panelPesquisaLayout.setHorizontalGroup(
            panelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPesquisar)
                    .addComponent(textPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPesquisaTelefone)
                    .addComponent(btnPesquisaNome))
                .addGap(18, 18, 18)
                .addComponent(btnPesquisar)
                .addContainerGap())
        );
        panelPesquisaLayout.setVerticalGroup(
            panelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPesquisaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPesquisaLayout.createSequentialGroup()
                        .addComponent(btnPesquisaNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPesquisaTelefone))
                    .addGroup(panelPesquisaLayout.createSequentialGroup()
                        .addGroup(panelPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPesquisar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelPesquisaLayout.createSequentialGroup()
                                .addComponent(labelPesquisar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );

        btnSelecionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/fic/poo/teleentrega/imagens/tick.png"))); // NOI18N
        btnSelecionar.setText("Selecionar");
        btnSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarActionPerformed(evt);
            }
        });

        btnFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/fic/poo/teleentrega/imagens/door_in.png"))); // NOI18N
        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(btnSelecionar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFechar)
                        .addGap(96, 96, 96)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSelecionar)
                    .addComponent(btnFechar))
                .addContainerGap())
        );

        bindingGroup.bind();

        setBounds(0, 0, 512, 390);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        //try { this.setClosed(true); }
        //catch (Exception e) { }
        this.hide();
        this.getDesktopPane().repaint();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarActionPerformed
        if (tablePesquisa.getSelectedRow() >= 0)
        {
            frameUsuario.selecionaCodigoUsuario(
                    listaUsuarios.get(
                            tablePesquisa.getSelectedRow()).getCodigo(), evt);
                    //alternativa:
                    //Integer.parseInt(
                    //tablePesquisa.getValueAt(tablePesquisa.getSelectedRow(),0).toString()) , evt);
            btnFecharActionPerformed(evt);
        }
        else
            JOptionPane.showMessageDialog(this,"Selecione um Usuário na Tabela...",
                    "Erro",JOptionPane.ERROR_MESSAGE);
        
    }//GEN-LAST:event_btnSelecionarActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        
        String[] dados = new String[4];
        String pesquisar;
        pesquisar = textPesquisar.getText();
        listaUsuarios = daoUsuario.listaUsuariosNome(pesquisar);
        
        DefaultTableModel modelo = (DefaultTableModel)tablePesquisa.getModel();
        while (modelo.getRowCount() > 0)
           modelo.removeRow(0);
        
        if (listaUsuarios != null)
        {
            for(Usuario u : listaUsuarios)
            {
                dados[0] = String.valueOf(u.getCodigo());
                dados[1] = u.getNome();
                dados[2] = u.getTelefone();
                dados[3] = u.getCpf();
                modelo.addRow(dados);
                //modelo.addRow(new String[] {String.valueOf(u.getCodigo()),
                //        u.getNome(),
                //        u.getTelefone(),
                //        u.getCpf()});
            }
        }
        else
            JOptionPane.showMessageDialog(this,"Pequisa Não Localizou Usuários Cadastrados",
                    "Erro",JOptionPane.ERROR_MESSAGE);

    }//GEN-LAST:event_btnPesquisarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFechar;
    private javax.swing.JRadioButton btnPesquisaNome;
    private javax.swing.JRadioButton btnPesquisaTelefone;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSelecionar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelPesquisar;
    private javax.swing.JPanel panelPesquisa;
    private javax.swing.JTable tablePesquisa;
    private javax.swing.JTextField textPesquisar;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
