package br.fic.poo.teleentrega.frames;

import br.fic.poo.teleentrega.util.ClasseUtil;
import java.awt.*;
import java.util.*;
import javax.swing.*;

/**
 *
 * @author francisco.newton
 */
public class FramePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FramePrincipal
     */
    public FramePrincipal() {
        initComponents();

        try {
           UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        }
        catch(Exception e)
        { e.printStackTrace(); }

        //desktopPane.setBackground(new Color(0,153,153));
        this.setTitle("FIC : POO - Atividade Estruturada 2012.2 - Sistema de Tele-Entregas");
        this.setIconImage(
             new javax.swing.ImageIcon(getClass().getResource("/br/fic/poo/teleentrega/imagens/tux.png"))
                .getImage());
        this.setLayout(new BorderLayout());
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.add(toolBar,BorderLayout.PAGE_START);
        this.add(desktop,"Center");
        this.add(statusLabel,"South");
        
        Calendar data = GregorianCalendar.getInstance();
        statusLabel.setText(
                " Sistema de Tele-Entregas : By Newton Gomes 2012  -  " 
                + data.get(Calendar.DATE) + " de " 
                + ClasseUtil.nomeMes(data.get(Calendar.MONTH)+1) + 
                " de " + data.get(Calendar.YEAR));
        
        new FrameLogin(this);

/*    
        JOptionPane.showMessageDialog(null,"Carregando Dados, Aguarde...");
        //forma Texto
        Biblioteca.getInstance().lerDados();
        //forma Objeto
        //try {
            //Biblioteca.getInstance().gravarBiblioteca();
        //    Biblioteca.getInstance().lerBiblioteca();
        //    JOptionPane.showMessageDialog(null,"Leitura do Arquivo realizada com sucesso.");
        //} catch(Exception e)
        //{
        //    JOptionPane.showMessageDialog(null,e.getMessage());
        //    e.printStackTrace();
        //}
        //Biblioteca.getInstance().gravarBiblioteca();
*/
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        toolBar = new javax.swing.JToolBar();
        btnClientes = new javax.swing.JButton();
        btnProdutos = new javax.swing.JButton();
        btnPedidos = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        statusLabel = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        mnuCadastros = new javax.swing.JMenu();
        mnuClientes = new javax.swing.JMenuItem();
        mnuProdutos = new javax.swing.JMenuItem();
        mnuEntregadores = new javax.swing.JMenuItem();
        mnuUsuarios = new javax.swing.JMenuItem();
        mnuPedidos = new javax.swing.JMenu();
        mnuNovoPedido = new javax.swing.JMenuItem();
        mnuFechaPedido = new javax.swing.JMenuItem();
        mnuPainelPedidos = new javax.swing.JMenuItem();
        mnuConsultas = new javax.swing.JMenu();
        mnuConsultaPedido = new javax.swing.JMenuItem();
        mnuListaPedidos = new javax.swing.JMenuItem();
        mnuSistema = new javax.swing.JMenu();
        mnuSair = new javax.swing.JMenuItem();
        mnuSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        desktop.setBackground(new java.awt.Color(0, 153, 153));

        toolBar.setRollover(true);

        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/fic/poo/teleentrega/imagens/16px-Gtk-dialog-question.png"))); // NOI18N
        btnClientes.setFocusable(false);
        btnClientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBar.add(btnClientes);

        btnProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/fic/poo/teleentrega/imagens/16px-Gtk-dialog-question.png"))); // NOI18N
        btnProdutos.setFocusable(false);
        btnProdutos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnProdutos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBar.add(btnProdutos);

        btnPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/fic/poo/teleentrega/imagens/16px-Gtk-dialog-question.png"))); // NOI18N
        btnPedidos.setFocusable(false);
        btnPedidos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPedidos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBar.add(btnPedidos);

        btnUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/fic/poo/teleentrega/imagens/user_suit.png"))); // NOI18N
        btnUsuarios.setToolTipText("Cadastro de Usuários");
        btnUsuarios.setFocusable(false);
        btnUsuarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUsuarios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });
        toolBar.add(btnUsuarios);

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/fic/poo/teleentrega/imagens/door_in.png"))); // NOI18N
        btnSair.setFocusable(false);
        btnSair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSair.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        toolBar.add(btnSair);

        statusLabel.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        statusLabel.setForeground(new java.awt.Color(0, 0, 153));
        statusLabel.setText(" Sistema de Tele-Entregas : By Newton Gomes 2012  -  DD de MMMMM de AAAA");

        mnuCadastros.setMnemonic('C');
        mnuCadastros.setText("Cadastros");

        mnuClientes.setMnemonic('o');
        mnuClientes.setText("Clientes");
        mnuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuClientesActionPerformed(evt);
            }
        });
        mnuCadastros.add(mnuClientes);

        mnuProdutos.setMnemonic('s');
        mnuProdutos.setText("Produtos");
        mnuProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuProdutosActionPerformed(evt);
            }
        });
        mnuCadastros.add(mnuProdutos);

        mnuEntregadores.setMnemonic('a');
        mnuEntregadores.setText("Entregadores");
        mnuEntregadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEntregadoresActionPerformed(evt);
            }
        });
        mnuCadastros.add(mnuEntregadores);

        mnuUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/fic/poo/teleentrega/imagens/user_suit.png"))); // NOI18N
        mnuUsuarios.setMnemonic('x');
        mnuUsuarios.setText("Usuários");
        mnuUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuUsuariosActionPerformed(evt);
            }
        });
        mnuCadastros.add(mnuUsuarios);

        menuBar.add(mnuCadastros);

        mnuPedidos.setMnemonic('P');
        mnuPedidos.setText("Pedidos");

        mnuNovoPedido.setMnemonic('t');
        mnuNovoPedido.setText("Novo Pedido");
        mnuNovoPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNovoPedidoActionPerformed(evt);
            }
        });
        mnuPedidos.add(mnuNovoPedido);

        mnuFechaPedido.setMnemonic('y');
        mnuFechaPedido.setText("Fechar Pedido");
        mnuPedidos.add(mnuFechaPedido);

        mnuPainelPedidos.setMnemonic('p');
        mnuPainelPedidos.setText("Painel de Pedidos");
        mnuPedidos.add(mnuPainelPedidos);

        menuBar.add(mnuPedidos);

        mnuConsultas.setMnemonic('n');
        mnuConsultas.setText("Consultas");

        mnuConsultaPedido.setText("Pedido para Entrega");
        mnuConsultas.add(mnuConsultaPedido);

        mnuListaPedidos.setText("Pedidos do Dia");
        mnuListaPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuListaPedidosActionPerformed(evt);
            }
        });
        mnuConsultas.add(mnuListaPedidos);

        menuBar.add(mnuConsultas);

        mnuSistema.setMnemonic('S');
        mnuSistema.setText("Sistema");

        mnuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/fic/poo/teleentrega/imagens/door_in.png"))); // NOI18N
        mnuSair.setMnemonic('r');
        mnuSair.setText("Sair");
        mnuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSairActionPerformed(evt);
            }
        });
        mnuSistema.add(mnuSair);

        mnuSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/fic/poo/teleentrega/imagens/16px-Gtk-dialog-question.png"))); // NOI18N
        mnuSobre.setMnemonic('S');
        mnuSobre.setText("Sobre...");
        mnuSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSobreActionPerformed(evt);
            }
        });
        mnuSistema.add(mnuSobre);

        menuBar.add(mnuSistema);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(toolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(desktop, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(statusLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(toolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(desktop, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(statusLabel)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuUsuariosActionPerformed
        if (frameUsuarios != null)
        {
            frameUsuarios.dispose();
        }
        frameUsuarios = new FrameUsuarios();
        desktop.add(frameUsuarios);
        ClasseUtil.centralizarInternalFrame(frameUsuarios);
        frameUsuarios.setVisible(true);
    }//GEN-LAST:event_mnuUsuariosActionPerformed

    private void mnuSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSobreActionPerformed
        new FrameSobre(this,true).setVisible(true);
    }//GEN-LAST:event_mnuSobreActionPerformed

    private void mnuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSairActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Confirma a Saída do Sistema ?",
                "Confirmação...",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE) == 
                JOptionPane.YES_OPTION)
        {
            //JOptionPane.showMessageDialog(null,"Gravando Dados, Aguarde...");
            //forma Texto
            //Biblioteca.getInstance().gravarDados();
            //forma Objeto
            //try {
            //Biblioteca.getInstance().gravarBiblioteca();
            //Biblioteca.getInstance().lerBiblioteca();
            //JOptionPane.showMessageDialog(null,"Gravação do Arquivo realizada com sucesso.");
            //} catch(Exception e)
            //{
            //    JOptionPane.showMessageDialog(null,e.getMessage());
            //}
            System.exit(0);
        }
    }//GEN-LAST:event_mnuSairActionPerformed

    private void mnuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuClientesActionPerformed
        if (frameClientes != null)
        {
            frameClientes.dispose();
        }
        frameClientes = new FrameClientes();
        desktop.add(frameClientes);
        ClasseUtil.centralizarInternalFrame(frameClientes);
        frameClientes.setVisible(true);
    }//GEN-LAST:event_mnuClientesActionPerformed

    private void mnuProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuProdutosActionPerformed
        if (frameProdutos != null)
        {
            frameProdutos.dispose();
        }
        frameProdutos = new FrameProdutos();
        desktop.add(frameProdutos);
        ClasseUtil.centralizarInternalFrame(frameProdutos);
        frameProdutos.setVisible(true);
    }//GEN-LAST:event_mnuProdutosActionPerformed

    private void mnuEntregadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEntregadoresActionPerformed
        if (frameEntregadores != null)
        {
            frameEntregadores.dispose();
        }
        frameEntregadores = new FrameEntregadores();
        desktop.add(frameEntregadores);
        ClasseUtil.centralizarInternalFrame(frameEntregadores);
        frameEntregadores.setVisible(true);
    }//GEN-LAST:event_mnuEntregadoresActionPerformed

private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
    mnuUsuariosActionPerformed(evt);
}//GEN-LAST:event_btnUsuariosActionPerformed

private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
    mnuSairActionPerformed(evt);   
}//GEN-LAST:event_btnSairActionPerformed

    private void mnuNovoPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNovoPedidoActionPerformed
        if (frameNovoPedido != null)
        {
            frameNovoPedido.dispose();
        }
        frameNovoPedido = new FrameNovoPedido();
        desktop.add(frameNovoPedido);
        ClasseUtil.centralizarInternalFrame(frameNovoPedido);
        frameNovoPedido.setVisible(true);
    }//GEN-LAST:event_mnuNovoPedidoActionPerformed

    private void mnuListaPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuListaPedidosActionPerformed
        if (frameConsultaPedidosDia != null)
        {
            frameConsultaPedidosDia.dispose();
        }
        frameConsultaPedidosDia = new FrameConsultaPedidosDia();
        desktop.add(frameConsultaPedidosDia);
        ClasseUtil.centralizarInternalFrame(frameConsultaPedidosDia);
        frameConsultaPedidosDia.setVisible(true);
    }//GEN-LAST:event_mnuListaPedidosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FramePrincipal().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnPedidos;
    private javax.swing.JButton btnProdutos;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu mnuCadastros;
    private javax.swing.JMenuItem mnuClientes;
    private javax.swing.JMenuItem mnuConsultaPedido;
    private javax.swing.JMenu mnuConsultas;
    private javax.swing.JMenuItem mnuEntregadores;
    private javax.swing.JMenuItem mnuFechaPedido;
    private javax.swing.JMenuItem mnuListaPedidos;
    private javax.swing.JMenuItem mnuNovoPedido;
    private javax.swing.JMenuItem mnuPainelPedidos;
    private javax.swing.JMenu mnuPedidos;
    private javax.swing.JMenuItem mnuProdutos;
    private javax.swing.JMenuItem mnuSair;
    private javax.swing.JMenu mnuSistema;
    private javax.swing.JMenuItem mnuSobre;
    private javax.swing.JMenuItem mnuUsuarios;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JToolBar toolBar;
    // End of variables declaration//GEN-END:variables

    private FrameClientes frameClientes;
    private FrameProdutos frameProdutos;
    private FrameEntregadores frameEntregadores;
    private FrameUsuarios frameUsuarios;
    private FrameNovoPedido frameNovoPedido;
    private FrameConsultaPedidosDia frameConsultaPedidosDia;


}
