
package br.fic.poo.teleentrega.frames;

import br.fic.poo.teleentrega.classes.Usuario;
import br.fic.poo.teleentrega.persistencia.UsuarioDAO;
import br.fic.poo.teleentrega.util.ClasseUtil;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;

/**
 *
 * @author francisco.newton
 */
public class FrameUsuarios extends javax.swing.JInternalFrame {

    private UsuarioDAO daoUsuario = new UsuarioDAO();
    /**
     * Creates new form FrameUsuarios
     */
    public FrameUsuarios() {
        initComponents();
        this.desabilitarBotoes();
        this.desabilitarCampos();
        textCodigo.setEnabled(true);
        btnBuscar.setEnabled(true);
        btnNovo.setEnabled(true);
        btnPesquisar.setEnabled(true);
    }
    
    private void desabilitarBotoes()
    {
        btnBuscar.setEnabled(false);
        btnNovo.setEnabled(false);
        btnPesquisar.setEnabled(false);
        btnGravar.setEnabled(false);
        btnCancelar.setEnabled(false);
        btnAlterar.setEnabled(false);;
        btnExcluir.setEnabled(false);
    }
    
    private void desabilitarCampos()
    {
        textCodigo.setEnabled(false);
        textNome.setEnabled(false);
        textCpf.setEnabled(false);
        textTelefone.setEnabled(false);
        textLogin.setEnabled(false);
        textSenha.setEnabled(false);
        textConfirmaSenha.setEnabled(false);
    }
    
    private void habilitarCampos()
    {
        textCodigo.setEnabled(true);
        textNome.setEnabled(true);
        textCpf.setEnabled(true);
        textTelefone.setEnabled(true);
        textLogin.setEnabled(true);
        textSenha.setEnabled(true);
        textConfirmaSenha.setEnabled(true);
    }
    
    private void limparCampos()
    {
        textCodigo.setText("");
        textNome.setText("");
        textCpf.setText("");
        textTelefone.setText("");
        textLogin.setText("");
        textSenha.setText("");
        textConfirmaSenha.setText("");
    }
    
    private Usuario lerCampos()
    {
        Usuario u = new Usuario();
        if (textCodigo.getText().isEmpty())
            u.setCodigo(0);
        else
            u.setCodigo(Integer.parseInt(textCodigo.getText()));
        u.setNome(textNome.getText());
        u.setTelefone(textTelefone.getText());
        u.setCpf(textCpf.getText());
        u.setLogin(textLogin.getText());
        u.setSenha(new String(textSenha.getPassword()));
        
        return u;
    }

    private void atualizarCampos(Usuario u)
    {
        textCodigo.setText(u.getCodigo()+"");
        textNome.setText(u.getNome());
        textTelefone.setText(u.getTelefone());
        textCpf.setText(u.getCpf());
        textLogin.setText(u.getLogin());
        textSenha.setText(u.getSenha());
        textConfirmaSenha.setText(u.getSenha());   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        labelCodigo = new javax.swing.JLabel();
        labelNome = new javax.swing.JLabel();
        labelCpf = new javax.swing.JLabel();
        labelTelefone = new javax.swing.JLabel();
        labelSenha = new javax.swing.JLabel();
        labelConfirmaSenha = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        btnGravar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        textCodigo = new javax.swing.JTextField();
        textNome = new javax.swing.JTextField();
        textCpf = new javax.swing.JFormattedTextField();
        textTelefone = new javax.swing.JFormattedTextField();
        textSenha = new javax.swing.JPasswordField();
        textConfirmaSenha = new javax.swing.JPasswordField();
        btnFechar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        labelLogin = new javax.swing.JLabel();
        textLogin = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Tele-Entregas - Cadastro de Usuários");
        setToolTipText("");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/br/fic/poo/teleentrega/imagens/user_suit.png"))); // NOI18N
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        labelTitulo.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(0, 0, 204));
        labelTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/fic/poo/teleentrega/imagens/48px-Crystal_Clear_app_kuser.png"))); // NOI18N
        labelTitulo.setText("Cadastro de Usuários do Sistema");

        labelCodigo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelCodigo.setForeground(new java.awt.Color(0, 0, 102));
        labelCodigo.setText("Código");

        labelNome.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelNome.setForeground(new java.awt.Color(0, 0, 102));
        labelNome.setText("Nome");

        labelCpf.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelCpf.setForeground(new java.awt.Color(0, 0, 102));
        labelCpf.setText("CPF");

        labelTelefone.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelTelefone.setForeground(new java.awt.Color(0, 0, 102));
        labelTelefone.setText("Telefone");

        labelSenha.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelSenha.setForeground(new java.awt.Color(0, 0, 102));
        labelSenha.setText("Senha de Acesso");

        labelConfirmaSenha.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelConfirmaSenha.setForeground(new java.awt.Color(0, 0, 102));
        labelConfirmaSenha.setText("Confirmação de Senha");

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/fic/poo/teleentrega/imagens/user.png"))); // NOI18N
        btnBuscar.setText(" Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/fic/poo/teleentrega/imagens/isimple_system_lnx-Icons-16X16-file_new.png-16x16.png"))); // NOI18N
        btnNovo.setText(" Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/fic/poo/teleentrega/imagens/isimple_system_lnx-Icons-16X16-app_search.png-16x16.png"))); // NOI18N
        btnPesquisar.setText(" Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        btnGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/fic/poo/teleentrega/imagens/disk.png"))); // NOI18N
        btnGravar.setText(" Gravar");
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/fic/poo/teleentrega/imagens/cross.png"))); // NOI18N
        btnCancelar.setText(" Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        try {
            textCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            textTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btnFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/fic/poo/teleentrega/imagens/door_in.png"))); // NOI18N
        btnFechar.setText(" Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/fic/poo/teleentrega/imagens/application_form_edit.png"))); // NOI18N
        btnAlterar.setText(" Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/fic/poo/teleentrega/imagens/delete.png"))); // NOI18N
        btnExcluir.setText(" Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        labelLogin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelLogin.setForeground(new java.awt.Color(0, 0, 102));
        labelLogin.setText("Login de Acesso");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btnGravar)
                        .addGap(50, 50, 50)
                        .addComponent(btnCancelar)
                        .addGap(54, 54, 54)
                        .addComponent(btnFechar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(labelTelefone)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(textTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(150, 150, 150)
                            .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelNome)
                                .addComponent(labelCpf))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(textCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(150, 150, 150)
                                    .addComponent(btnAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelConfirmaSenha)
                            .addComponent(labelSenha)
                            .addComponent(labelLogin))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textSenha)
                            .addComponent(textConfirmaSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                            .addComponent(textLogin)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelCodigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(btnNovo)
                        .addGap(18, 18, 18)
                        .addComponent(btnPesquisar)))
                .addGap(14, 14, 14))
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(labelTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCodigo)
                    .addComponent(btnBuscar)
                    .addComponent(btnNovo)
                    .addComponent(textCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome)
                    .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCpf)
                    .addComponent(textCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlterar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTelefone)
                    .addComponent(textTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLogin)
                    .addComponent(textLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSenha)
                    .addComponent(textSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelConfirmaSenha)
                    .addComponent(textConfirmaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnGravar)
                    .addComponent(btnFechar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        //this.hide();
        //this.getDesktopPane().repaint();
        try { this.setClosed(true); }
        catch (Exception e) { }
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        JDesktopPane desktop = this.getDesktopPane();
        if (framePesquisa == null)
        {
            framePesquisa = new FramePesquisaUsuarios(this,daoUsuario);
            desktop.add(framePesquisa);
            ClasseUtil.centralizarInternalFrame(framePesquisa);
        }
        framePesquisa.setVisible(true);
    }//GEN-LAST:event_btnPesquisarActionPerformed

    public void selecionaCodigoUsuario(int codigo,java.awt.event.ActionEvent evt)
    {
        textCodigo.setText(codigo+"");
        btnBuscarActionPerformed(evt);
    }
    
    
    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        if (framePesquisa != null)
        {
            framePesquisa.dispose();
        }
    }//GEN-LAST:event_formInternalFrameClosing

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        this.limparCampos();
        this.desabilitarBotoes();
        this.habilitarCampos();
        btnGravar.setEnabled(true);
        btnCancelar.setEnabled(true);
        textCodigo.setEnabled(false);
        textNome.requestFocus();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.limparCampos();
        this.desabilitarBotoes();
        this.desabilitarCampos();
        textCodigo.setEnabled(true);
        btnBuscar.setEnabled(true);
        btnNovo.setEnabled(true);
        btnPesquisar.setEnabled(true);
        textCodigo.requestFocus();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        Usuario usuario = this.lerCampos();

        if (! usuario.getSenha().equals(new String(textConfirmaSenha.getPassword())))
        {
            JOptionPane.showMessageDialog(this, 
                        "Erro : Senha/Confirmação não confere.",
                        "Erro!",JOptionPane.ERROR_MESSAGE);
            return;
        }
           
        if (textCodigo.getText().isEmpty())   // Inclusão de Cadastro
        {
            if (daoUsuario.incluir(usuario))
            {
                JOptionPane.showMessageDialog(this, 
                        "Registro incluido com sucesso.");
                textCodigo.setText(usuario.getCodigo()+"");
            }
            else
            {
                JOptionPane.showMessageDialog(this, 
                    "Erro na inclusão do Registro.","Erro!",
                    JOptionPane.ERROR_MESSAGE);
                this.limparCampos();
            }
        }
        else  ///// Alteração de Cadastro
        {
            if (daoUsuario.alterar(usuario))
            {
                JOptionPane.showMessageDialog(this, 
                        "Registro alterado com sucesso.");
            }
            else
            {
                JOptionPane.showMessageDialog(this, 
                    "Erro na alteração do Registro.","Erro!",
                    JOptionPane.ERROR_MESSAGE);
                this.limparCampos();
            }
        }

        this.desabilitarBotoes();
        this.desabilitarCampos();
        textCodigo.setEnabled(true);
        btnBuscar.setEnabled(true);
        btnNovo.setEnabled(true);
        btnPesquisar.setEnabled(true);
        textCodigo.requestFocus();
    }//GEN-LAST:event_btnGravarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        Usuario usuario;
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        String pesquisar = textCodigo.getText();
        this.limparCampos();
        
        if (pesquisar.isEmpty())
        {
            JOptionPane.showMessageDialog(this, 
                    "Erro : Preencha o valor do código para buscar...",
                    "Erro!",JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        usuario = daoUsuario.consultar(Integer.parseInt(pesquisar));
        if (usuario == null)
        {
            JOptionPane.showMessageDialog(this, 
                    "Erro : Código do Usuário Não Localizado.",
                    "Erro!",JOptionPane.ERROR_MESSAGE);
            return;
        }

        this.atualizarCampos(usuario);
        btnAlterar.setEnabled(true);
        btnExcluir.setEnabled(true);
        textCodigo.requestFocus();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        this.desabilitarBotoes();
        this.habilitarCampos();
        btnGravar.setEnabled(true);
        btnCancelar.setEnabled(true);
        textCodigo.setEnabled(false);
        textNome.requestFocus();
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (JOptionPane.showConfirmDialog(this,"Deseja excluir o Usuario:\n"+
                textCodigo.getText()+"-"+textNome.getText()+" ?","Confirma Exclusão...",
                JOptionPane.YES_NO_CANCEL_OPTION,JOptionPane.QUESTION_MESSAGE) == 
                JOptionPane.YES_OPTION)
        {
            if (daoUsuario.excluir(Integer.parseInt(textCodigo.getText())))
            {
                JOptionPane.showMessageDialog(this, 
                        "Registro Excluído com sucesso.");
                this.limparCampos();
                this.desabilitarBotoes();
                btnBuscar.setEnabled(true);
                btnNovo.setEnabled(true);
                btnPesquisar.setEnabled(true);
                textCodigo.requestFocus();
            }
            else
            {
                JOptionPane.showMessageDialog(this, 
                    "Erro na exclusão do Registro.","Erro!",
                    JOptionPane.ERROR_MESSAGE);
            }                
        }

    }//GEN-LAST:event_btnExcluirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JLabel labelCodigo;
    private javax.swing.JLabel labelConfirmaSenha;
    private javax.swing.JLabel labelCpf;
    private javax.swing.JLabel labelLogin;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelSenha;
    private javax.swing.JLabel labelTelefone;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JTextField textCodigo;
    private javax.swing.JPasswordField textConfirmaSenha;
    private javax.swing.JFormattedTextField textCpf;
    private javax.swing.JTextField textLogin;
    private javax.swing.JTextField textNome;
    private javax.swing.JPasswordField textSenha;
    private javax.swing.JFormattedTextField textTelefone;
    // End of variables declaration//GEN-END:variables

    FramePesquisaUsuarios framePesquisa;
}
