package br.estacio.poo.alunos.frames;

import br.estacio.poo.alunos.dao.UsuarioDAO;
import br.estacio.poo.alunos.util.ClasseUtil;
import java.awt.BorderLayout;
import java.awt.Color;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Newton
 */
public class FramePrincipal extends JFrame {

    private String[] nomeMes = {"Janeiro", "Fevereiro",
        "Março", "Abril", "Maio", "Junho", "Julho",
        "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro"};
    
    //public static DadosAgencia dadosAgencia;
    
    private FrameUsuario frameUsuario = null;
    private FrameAluno frameAluno = null;
    private FrameTurma frameTurma = null;
    private UsuarioDAO daoUsuario = null;
    
    public FramePrincipal() {
        
        initComponents();

        setLayout(new BorderLayout());
        desktop.setBackground(Color.GRAY);
        add(desktop,"Center");
        add(lblStatus,"South");

        try 
        {
           UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        }
        catch(Exception e)
        { e.printStackTrace(); }
        
        this.setIconImage(
             new javax.swing.ImageIcon(getClass().getResource(
                "/br/estacio/poo/alunos/imagens/icon_aluno12.jpg"))
                .getImage());

        Calendar data = GregorianCalendar.getInstance();
        lblStatus.setText(
                " Projeto para Cadastro de Alunos : By Newton Gomes 2014.2  -  " 
                + data.get(Calendar.DATE) + " de " 
                + nomeMes[data.get(Calendar.MONTH)] + 
                " de " + data.get(Calendar.YEAR));
        
        setExtendedState(MAXIMIZED_BOTH);  
        setVisible(false);
        
        // Testando conexão com Banco de Dados
        //java.sql.Connection conn =
        //new br.estacio.poo.alunos.persistencia.ConnectionFactory().getDerbyConnection();
        //JOptionPane.showMessageDialog(null, "Conexão com Banco de Dados criada.");
        // Criando DAOs
        //daoUsuario = new UsuarioDAO();
        
        // Criando tabelas no Banco de Dados
        //daoUsuario.createTable();
        
        
        
        new FrameLogin(this);
    }

    public void acessar()
    {
        this.setVisible(true);
    }
    
    private void confirmarSaida()
    {
      if (JOptionPane.showConfirmDialog(this,  
          "Deseja Sair do Cadastro de Alunos ?", 
          "Saída do Sistema...",
          JOptionPane.YES_NO_CANCEL_OPTION) == JOptionPane.YES_OPTION)
        System.exit(0);
    }    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        turma1 = new br.estacio.poo.alunos.entidade.Turma();
        desktop = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuCadastros = new javax.swing.JMenu();
        mnuCadAlunos = new javax.swing.JMenuItem();
        mnuCadTurmas = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuCadUsuarios = new javax.swing.JMenuItem();
        mnuMatriculas = new javax.swing.JMenu();
        mnuMatricularAluno = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        mnuConsultas = new javax.swing.JMenu();
        mnuConAlunos = new javax.swing.JMenuItem();
        mnuConTurmas = new javax.swing.JMenuItem();
        mnuSistema = new javax.swing.JMenu();
        mnuSobre = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnuSair = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("POO-2014-2 : Cadastro de Alunos");

        desktop.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/estacio/poo/alunos/imagens/alunos2.jpg"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Estácio - POO 2014.2");

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cadastro de Alunos V2");

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(desktopLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(desktopLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(304, Short.MAX_VALUE))
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(73, Short.MAX_VALUE))
        );
        desktop.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblStatus.setText("Sistema - data");

        mnuCadastros.setMnemonic('C');
        mnuCadastros.setText("Cadastros");

        mnuCadAlunos.setText("Alunos");
        mnuCadAlunos.setName("A"); // NOI18N
        mnuCadAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadAlunosActionPerformed(evt);
            }
        });
        mnuCadastros.add(mnuCadAlunos);

        mnuCadTurmas.setText("Turmas");
        mnuCadTurmas.setName("T"); // NOI18N
        mnuCadTurmas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadTurmasActionPerformed(evt);
            }
        });
        mnuCadastros.add(mnuCadTurmas);
        mnuCadastros.add(jSeparator1);

        mnuCadUsuarios.setText("Usuários");
        mnuCadUsuarios.setName("U"); // NOI18N
        mnuCadUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadUsuariosActionPerformed(evt);
            }
        });
        mnuCadastros.add(mnuCadUsuarios);

        jMenuBar1.add(mnuCadastros);

        mnuMatriculas.setMnemonic('M');
        mnuMatriculas.setText("Matrículas");

        mnuMatricularAluno.setText("Matricular Alunos");
        mnuMatriculas.add(mnuMatricularAluno);

        jMenuItem1.setText("Lançamento de Notas");
        mnuMatriculas.add(jMenuItem1);

        jMenuBar1.add(mnuMatriculas);

        mnuConsultas.setMnemonic('n');
        mnuConsultas.setText("Consultas");

        mnuConAlunos.setText("Alunos");
        mnuConsultas.add(mnuConAlunos);

        mnuConTurmas.setText("Turmas de Alunos");
        mnuConsultas.add(mnuConTurmas);

        jMenuBar1.add(mnuConsultas);

        mnuSistema.setMnemonic('S');
        mnuSistema.setText("Sistema");

        mnuSobre.setMnemonic('S');
        mnuSobre.setText("Sobre...");
        mnuSistema.add(mnuSobre);
        mnuSistema.add(jSeparator2);

        mnuSair.setMnemonic('r');
        mnuSair.setText("Sair do Sistema");
        mnuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSairActionPerformed(evt);
            }
        });
        mnuSistema.add(mnuSair);

        jMenuBar1.add(mnuSistema);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(desktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblStatus)
                .addGap(25, 25, 25))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSairActionPerformed
        this.confirmarSaida();
    }//GEN-LAST:event_mnuSairActionPerformed

    private void mnuCadUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadUsuariosActionPerformed
        if (frameUsuario == null)
        {
            frameUsuario = new FrameUsuario();
            desktop.add(frameUsuario);
        }
        ClasseUtil.centralizarInternalFrame(frameUsuario);
        frameUsuario.inicializar();
        frameUsuario.setVisible(true);
        frameUsuario.moveToFront();
    }//GEN-LAST:event_mnuCadUsuariosActionPerformed

    private void mnuCadAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadAlunosActionPerformed
        if (frameAluno == null)
        {
            frameAluno = new FrameAluno();
            desktop.add(frameAluno);
        }
        ClasseUtil.centralizarInternalFrame(frameAluno);
        frameAluno.inicializar();
        frameAluno.setVisible(true);
        frameAluno.moveToFront();
    }//GEN-LAST:event_mnuCadAlunosActionPerformed

    private void mnuCadTurmasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadTurmasActionPerformed
        if (frameTurma == null)
        {
            frameTurma = new FrameTurma();
            desktop.add(frameTurma);
        }
        ClasseUtil.centralizarInternalFrame(frameTurma);
        frameTurma.inicializar();
        frameTurma.setVisible(true);
        frameTurma.moveToFront();
    }//GEN-LAST:event_mnuCadTurmasActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JMenuItem mnuCadAlunos;
    private javax.swing.JMenuItem mnuCadTurmas;
    private javax.swing.JMenuItem mnuCadUsuarios;
    private javax.swing.JMenu mnuCadastros;
    private javax.swing.JMenuItem mnuConAlunos;
    private javax.swing.JMenuItem mnuConTurmas;
    private javax.swing.JMenu mnuConsultas;
    private javax.swing.JMenuItem mnuMatricularAluno;
    private javax.swing.JMenu mnuMatriculas;
    private javax.swing.JMenuItem mnuSair;
    private javax.swing.JMenu mnuSistema;
    private javax.swing.JMenuItem mnuSobre;
    private br.estacio.poo.alunos.entidade.Turma turma1;
    // End of variables declaration//GEN-END:variables
}
