package br.estacio.poo.alunos.frames;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Newton
 */
public class TabelaTeste extends javax.swing.JFrame {

    /**
     * Creates new form TabelaTeste
     */
    public TabelaTeste() {
        initComponents();
        
        //DefaultTableModel modelo = new DefaultTableModel();
        //tabela não-editável:
        DefaultTableModel modelo = 
                new DefaultTableModel(null,new Object[]{}) 
                {
                 public boolean isCellEditable(int row, int col)
                 {  return false; } 
                };
        
        modelo.addColumn("Matrícula");
        modelo.addColumn("Nome do Aluno");
        modelo.addColumn("Curso");
        //tablePesquisa.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        //tablePesquisa.getTableHeader().setReorderingAllowed(false); //Não deixa o usuário mexer na sequencia das colunas  
        //tablePesquisa.getColumnModel().getColumn(0).setPreferredWidth(5); //largura da coluna  
        //tablePesquisa.getColumnModel().getColumn(1).setPreferredWidth(50); //largura da coluna    
        //tablePesquisa.setSelectionMode(ListSelectionModel.SINGLE_SELECTION); //permite selecionar apenas uma linha na tabela          //tablePesquisa.getColumnModel().getColumn(0).setMaxWidth(10);
        //tablePesquisa.getTableHeader().getColumnModel().getColumn(1).setMaxWidth(20);
        //tablePesquisa.getColumnModel().getColumn(0).setPreferredWidth(20);
        //tablePesquisa.getColumnModel().getColumn(1).setMaxWidth(10);
        //tablePesquisa.getColumnModel().getColumn(2).setMinWidth(30);
        //tablePesquisa.getColumnModel().getColumn(3).setWidth(40);
        //tablePesquisa.getTableHeader().getColumnModel(3).getColumn(3).setWidth(20);
        tabAlunos.setModel(modelo);

        String[] dados = new String[3];

        DefaultTableModel modelo1 = (DefaultTableModel)tabAlunos.getModel();
        
        while (modelo1.getRowCount() > 0)
           modelo.removeRow(0);
        
        dados[0] = "100";
        dados[1] = "Pedro";
        dados[2] = "SI";
        modelo1.addRow(dados);

        dados[0] = "101";
        dados[1] = "Alana";
        dados[2] = "ADS";
        modelo1.addRow(dados);

        dados[0] = "102";
        dados[1] = "Igor";
        dados[2] = "Redes";
        modelo1.addRow(dados);

        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabAlunos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabAlunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabAlunos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TabelaTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TabelaTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TabelaTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TabelaTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TabelaTeste().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabAlunos;
    // End of variables declaration//GEN-END:variables
}
